apiVersion: v1
kind: ConfigMap
metadata:
  name: automation-scripts
data:
  trigger-workflow.sh: |
    [ -z "$1" ] && echo "[X] Must supply an argument for REPO."; exit 1
    [ -z "$2" ] && echo "[X] Must supply an argument for WORKFLOW_ID."; exit 1

    echo "Triggering workflow '$1'..."
    curl -L \
      -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $TOKEN" \
      https://api.github.com/repos/$1/actions/workflows/$2/dispatches \
      -d '{"ref":"topic-branch","inputs":{"name":"Mona the Octocat","home":"San Francisco, CA"}}'
  check-image.sh: |
    adwwa
  check-workflow.sh: |
    [ -z "$1" ] && echo "[X] Must supply an argument for WORKFLOW_ID."; exit 1

    echo "Checking status of workflow '$1'..."
    state=$(curl -L \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $TOKEN" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      https://api.github.com/repos/$REPO/actions/workflows/$1 \
      | jq .state
    )

    # Activate if inactive
    if [ $state != "active" ]; then
      echo "> Workflow is inactive ($state), enabling..."
      curl -L \
        -X PUT \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/$REPO/actions/workflows/$1/enable
    fi
