name: build-publish-summerwind

on:
  push:
    branches:
      - "master"
    paths:
      - "summerwind/*ocker*"
      - "summerwind/run.sh"
      - ".github/workflows/*summerwind.yaml"
  schedule:
    - cron:  '0 1 1,14 * 1'
  workflow_dispatch:

jobs:
  build-summerwind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: summerwind
          platforms: linux/amd64,linux/arm64
          push: true
          tags: thisisnttheway/${{ github.event.repository.name }}-summerwind:latest