name: build-publish-custom

on:
  push:
    branches:
      - "master"
    paths:
      - "custom/*ocker*"
      - "custom/un.sh"
      - ".github/workflows/*custom.yaml"
  schedule:
    - cron:  '0 1 1,14 * 1'
  workflow_dispatch:

jobs:
  build-custom:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest GH runner release
        id: gh-runner-version
        run: |
          version=$(curl --silent "https://api.github.com/repos/actions/runner/releases/latest" |
            grep '"tag_name":' |
            sed -E 's/.*"([^"]+)".*/\1/' |
            sed -E 's/v//')
          echo "GH_RUN_VERSION=$version" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: custom
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            "GH_RUNNER_VERSION=${{ steps.gh-runner-version.outputs.GH_RUN_VERSION }}"
          tags: thisisnttheway/${{ github.event.repository.name }}-custom:latest